default:
    command:
        history:
            filename: ../../cmdhist.pcap
        port: 3075

    sequence:
        directory: ../sequences

    script:
        directory: ../scripts

    cmddict:
        filename:  cmd.yaml

    evrdict:
        filename:  evr.yaml

    tlmdict:
        filename:  tlm.yaml

    limits:
        filename:  limits.yaml
      
    table:
        filename: table.yaml

    bsc:
        filename: bsc.yaml

    dsn:
        sle:
            initiator_id: LSE
            # password only matters if we're doing auth and can stay as 'pw'
            password: pw
            responder_id: SSC
            # peer password only matters if we're doing auth and can stay as 'pw'
            peer_password: pw
            downlink_frame_type: TMTransFrame
            heartbeat: 25
            deadfactor: 5
            buffer_size: 256000
            responder_port: 'default'
            rcf:
                inst_id: sagr=LSE-SSC.spack=Test.rsl-fg=1.rcf=onlc2
                hostnames:
                    - example.hostname.1
                    - example.hostname.2
                port: None
                version: 4
                spacecraft_id: 250
                trans_frame_ver_num: 0
                auth_level: 'none'
            raf:
                inst_id: sagr=LSE-SSC.spack=Test.rsl-fg=1.raf=onlc1
                hostnames:
                    - example.hostname.1
                    - example.hostname.2
                port: None
                version: 4
                auth_level: 'none'
            fcltu:
                inst_id: None
                hostnames:
                    - example.hostname.1
                    - example.hostname.2
                port: None
                version: 4
                auth_level: 'none'

        cfdp:
            mib:
                path: ./mib
            datasink:
                outgoing:
                    path: ../ait/dsn/cfdp/datasink/outgoing
                incoming:
                    path: ../ait/dsn/cfdp/datasink/incoming
                tempfiles:
                    path: ../ait/dsn/cfdp/datasink/tempfiles
                pdusink:
                    path: ../ait/dsn/cfdp/datasink/pdusink
            max_file_name_length: 64
            max_entity_id_length: 8
            max_transaction_id_length: 8

    logging:
        name: ait
        hostname: yourCustomHostForLogging

    leapseconds:
        filename: leapseconds.dat

    notifications:
        email:
            # Specifies the triggers for which a type of notification
            # (email, text) will be emitted.
            triggers:
                - limit-warn
                - limit-error
            recipients:
                - email@address.com
        text:
            triggers:
                - limit-warn
                - limit-error
            # Most wireless carriers provide SMS gateways for sending
            # texts via email. You can look up the address format for your
            # given carrier. A list of some popular carriers is below:
            # AT&Tnumber@txt.att.net
            # Sprintnumber@messaging.sprintpcs.com
            # T-Mobilenumber@tmomail.net
            # Verizonnumber@vtext.com
            recipients:
                - phonenumber@service.com
        # Notifications require connection to an SMTP server for sending
        # both emails and texts. You should configure this to point to
        # your SMTP server with your credentials. You can use GMails
        # servers if you have a GMail account.
        smtp:
            server: smtp.gmail.com
            port: 465
            username: yourSMTPServerUsername
            password: yourSMTPServerPassword
        options:
            frequency: 25
            threshold: 1

    phase: 'dev'

    data:
        '1553':
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/1553
        bad:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/bad
        lehx:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/lehx
        planning:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/planning
        sdos:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/sdos
        uplink:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/uplink
        ats:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/ats

### SQLite3
    # database:
    #     dbname: </location/to/ait.db>

### InfluxDB
    # database:
    #     dbname: ait

    server:
        plugins: 
            - plugin:
                name: ait.gui.AITGUIPlugin
                inputs:
                    - log_stream
                    - telem_stream
                outputs:
                    - command_stream

### SQLite3
            # - plugin:
            #     name: ait.core.server.plugins.data_archive.DataArchive
            #     inputs:
            #         - telem_stream
            #     datastore: ait.core.db.SQLiteBackend

### InfluxDB
            # - plugin:
            #     name: ait.core.server.plugins.data_archive.DataArchive
            #     inputs:
            #         - telem_stream
            #         - <port number e.g. 8086>
            #     datastore: ait.core.db.InfluxDBBackend

        inbound-streams:
            - stream:
                name: log_stream
                input: 
                    - 2514

            - stream:
                name: telem_stream
                input: 
                    - 3076
### PacketHandler
                handlers:
                    - name: ait.core.server.handlers.PacketHandler
                      packet: 1553_HS_Packet

### CCSDSPacketHandler
                # handlers:
                #     - name: ait.core.server.handlers.CCSDSPacketHandler
                #       packet_types:   {'01011100111' : 'CCSDS_HEADER'}        #e.g.

        outbound-streams:
            - stream:
                name: command_stream
                output: 3075
